name: 'Make a Common Lisp Program'
description: >-
  Make a Common Lisp program running a specific Common Lisp system
branding:
  icon: box
  color: blue
inputs:
  implementation:
    description: |
      The Common Lisp implementation to use. This can be one of the
      following values:

        sbcl

      in the future we would like to support all of

        abcl clasp clisp ecl gcl sbcl
      
    default: 'sbcl'

  system:
    description: |
      The Common Lisp system to load.
    required: true

outputs:
  build-pathname:
    description: |
      The pathname to the produced program.
    value: ${{ steps.configure.outputs.build-pathname }}

runs:
  using: 'composite'
  steps:
    - name: 'Configure program preparation'
      id: configure
      shell: sh
      run: |
        ${GITHUB_ACTION_PATH}/with_lisp_implementation ${{ inputs.implementation }} <<EOF
        (ql:quickload '#:org.melusina.github-action.make-common-lisp-program)
        (org.melusina.github-action.make-common-lisp-program:configure)
        EOF
      env:
        LISP_SYSTEM: ${{ inputs.system }}

    - name: 'Trace the output of configuration'
      shell: sh
      run: |
        cat <<EOF
        implementation: ${{ steps.configure.outputs.implementation }}
        system: ${{ steps.configure.outputs.system }}
        build-pathname: ${{ steps.configure.outputs.build-pathname }}
        EOF

    - name: 'Trace the output of configuration'
      shell: sh
      run: |
        cat <<EOF
        implementation: ${{ steps.configure.outputs.implementation }}
        system: ${{ steps.configure.outputs.system }}
        EOF

    - name: 'Build Common Lisp program'
      uses: melusina-org/asdf-operate@v1
      with:
        implementation: ${{ inputs.implementation }}
        system: ${{ steps.configure.outputs.system }}
        operation: asdf:program-op

    - name: 'Ensure Common Lisp program has been built'
      shell: sh
      run: |
        test -x ${{ steps.configure.outputs.build-pathname }}

